# -*- coding: utf-8 -*-

insults = (
    "To call you stupid would be an insult to stupid people! I’ve known sheep that could outwit you. I’ve worn shoes with higher IQ.",
    "You are a sad strange little man, and you have my pity.",
    "I fart in your general direction. Your mother was a hamster and your father smelt of elderberries.",
    "Play cool now, but there’s one man too many in this chat and I think it’s you.",
    "Your brain’s so minute that if a hungry cannibal cracked your head open, there wouldn’t be enough to cover a small water biscuit.",
    "You are so fat and lazy I'd need two pokeflutes to wake you up",
    "If your gaming habits were a dress code, they'd be casual",
    "I fucked your grandmother and didn't even buy her dinner",
    "If i wanted to listen to an asshole speaking I would fart in a microphone", "You define autism",
    "I bet you were the most popular home-schooled kid in your class",
    "You have enough extra chromosomes to make a smarter clone of yourself",
    "You look like your mum pressed B while you were evolving",
    "If I wrote a recommendation for you, the reader would think it's a detailed case study of neurodegenerative disorders.",
    "There are millions of particles in the universe that we can observe, your mama took the ugly ones and put them into one nerd.",
    "You're not optimized for life are you?",
    "You are so technologically illiterate, you shake your laptop to get the cookies out",
    "You are a fart factory, slug-slimed sack of rat guts in cat vomit. A cheesy scab picked pimple squeezing finger bandage. A week old maggot burger with everything on it and flies on the side.",
    "It gives me a headache just trying to think down to your level.",
    "Shut up now or I will replace you with a very small shell script.",
    "You’re not a complete idiot… some parts are missing.",
    "You are very ugly and stupid and persistently wear a ridiculous hat which you should be ashamed of.",
    "You’re like a trained ape, only without the training.",
    "You’re so stupid, you think a thesaurus is a monster from Jurassic Park.",
    "Copernicus just called: you’re not the center of the universe.",
    "Look, we all have something to bring to this discussion. But I think from now on the thing you should bring is silence.",
    "MS-DOS can function at higher levels of sentience than you",
    "Let's just say you're not the fastest node in the cluster.",
    "Let's just say you're not the fastest disk in the RAID.",
    "Your mother's so fat she breaks for loops",
    "Maybe you should go back to Windows.",
    "Your mum is so fat her max file size is 4GB!",
    "You'll never be half the man your mother is.",
    "If my dog had your face I'd shave his butt and teach him to walk backwards.",
    "Everyone who has ever loved you was wrong",
    "You have small tits for a fat girl.",
    "You're blue waffles testimonial. You are a regurgitated anal-cum bubble",
    "You are Puddu's illegitimate son",
    "May I suggest you stop embarassing yourself playing Nexuiz and go back to minesweeper?"
)

